R11DT-1465: add parent chain to onScriptError
OutSystems/requirejs pull request #22
Opened 2023-02-02 16:23 UTC by osjlopes

### Context
This PR proposes changes to the `onScriptError` and` makerror` methods, to include in the generated error object, the files that depend on the file that failed to load (known as parents).

Before the implementation, requirejs would only lookup for the direct parent and only log it in the error object. Now, we append the complete parent list, so we can later invalidate the whole parent chain to be requested again.

As for tests, the new requirejs implementation was copied into my local platform and manually included in the `client-runtime-core` and `client-runtime` `node_modules` folders: No issues were found during runtime and while executing the repository test.

2023-02-02 17:45 UTC, joaomurgeiro-outsystems submitted a review, later dismissed
Looks good to me!

2023-02-03 08:59 UTC, hloOutSystems reviewed
I think it looks good to me, but I have little context on this topic.

2023-02-03 09:59 UTC, RicardoOS11 approved these changes, later dismissed
All good to me

2023-02-03 10:02 UTC, oscsx requested changes
Maybe we can add a test to check that this property is being correctly filled? We can probably base that test on this one: https://github.com/OutSystems/requirejs/blob/R11DT-1465-onScriptError-callback-changes/tests/error/errorChild.html

2023-02-03 10:02 UTC, oscsx commented on require.js
> +                var originalAttrId = attrId = getScriptData(evt).id;
I rather have a variable declaration per line. It's easier to understand and maintain. Also, this approach has some scoping issues: https://stackoverflow.com/a/1758912

2023-02-03 10:28 UTC, osjlopes commented on require.js
> +                var originalAttrId = attrId = getScriptData(evt).id;
Done!

2023-02-07 14:41 UTC, osjlopes commented
> Maybe we can add a test to check that this property is being correctly filled? We can probably base that test on this one: https://github.com/OutSystems/requirejs/blob/R11DT-1465-onScriptError-callback-changes/tests/error/errorChild.html

Added the test and confirmed the same fails if the fix is not present

2023-02-07 16:40 UTC, oscsx approved these changes
💪

2023-02-07 16:48 UTC, merged